services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25564:25565"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 4G
      MAX_MEMORY: 14G
      TYPE: FABRIC
      FABRIC_LOADER_VERSION: 0.16.10
      VERSION: 1.21.1
    volumes:
      - ./data:/data