services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
      FABRIC_LAUNCHER_VERSION: 0.10.2
      FABRIC_LOADER_VERSION: 0.16.10
      INIT_MEMORY: 4G
      MAX_MEMORY: 22G
      VERSION: 1.21.5
    volumes:
      - ./data:/data