services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 4G
      MAX_MEMORY: 12G
      TYPE: FABRIC
      VERSION: 1.18.2
      MODRINTH_PROJECTS: "fabric-api, macaws-stairs, macaws-fences-and-walls, macaws-furniture, macaws-windows, macaws-doors, chipped, travelersbackpack, supplementaries, rei, harvest-with-ease, beautify, connectiblechains, biomes-in-jars, terralith, yungs-api, yungs-better-nether-fortresses, yungs-better-mineshafts, yungs-better-strongholds, yungs-better-witch-huts, yungs-better-jungle-temples, yungs-better-end-island, yungs-better-desert-temples"
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
    volumes:
      - ./data:/data