services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 4G
      MAX_MEMORY: 12G
      TYPE: FABRIC
      VERSION: 1.18.2
      MODRINTH_PROJECTS: "travelersbackpack, chipped"
    volumes:
      - ./data:/data